version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: chat-back
    restart: always
    ports:
      - 6543:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: chat-db